version: '3.7'
services:
  backend:
    build: .
    ports:
      - 8080:80
    environment:
      - SERVICE_PORT=80
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
      - AWS_REGION=eu-west-1
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - S3_BUCKET_NAME=bsdapp-rap-audio
      - S3_ENDPOINT=http://localstack:4572
    depends_on:
      - localstack
    links:
      - localstack
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'