version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:80"
    environment:
      - SERVICE_PORT=80
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
  flyway:
    image: flyway/flyway:6.2.0-alpine
    restart: on-failure
    command: -url=jdbc:postgresql://db:5432/postgres -schemas=bsdac_api -user=postgres -password=postgres migrate
    volumes:
      - ./flyway/bsdac_api:/flyway/sql
    depends_on:
      - db
  db:
    image: "postgres:12.1-alpine"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres