version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:80"
  flyway:
    image: flyway/flyway:6.2.0-alpine
    restart: on-failure
    command: -url=jdbc:postgresql://db:5432/postgres -schemas=bsdac_api -user=postgres -password=postgres migrate
    volumes:
      - ./flyway/bsdac_api:/flyway/sql
    depends_on:
      - db
  db:
    image: "postgres:12.1-alpine"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres