version: '3'
services:
  backend:
    build: .
    ports:
      - 8080:80
    environment:
      - SERVICE_PORT=80
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
      - AWS_REGION=eu-west-1
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - 8000:8000