version: '3.7'
services:
  frontend:
    build: ./client
    ports:
      - 9001:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.priority=1"
  backend:
    build: ./server
    ports:
      - 9002:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api/`)"
      - "traefik.http.routers.backend.priority=2"
    environment:
      - SERVICE_PORT=80
      - LOGIN_EMAIL=test@bsdac.com
      - LOGIN_PASSWORD_SHA256=9F86D081884C7D659A2FEAA0C55AD015A3BF4F1B2B0B822CD15D6C15B0F00A08
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
      - AWS_REGION=eu-west-1
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - S3_BUCKET_NAME=bsdapp-rap-audio
      - S3_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack
    links:
      - localstack
  # Infra simulators
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3,dynamodb
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './server/.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'