openapi: 3.0.0
info:
  description: An API for retrieving resources related to Big Smash Day and Cube.
  version: "0.1.0"
  title: BSDAC API
  contact:
    email: campbelljip@gmail.com
paths:
  /raps/get-all:
    get:
      summary: Retrieves all raps
      description: |
        Retrieves all existing raps
      responses:
        '200':
          description: All the raps
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rap'
  /raps/stream/{id}:
    get:
      summary: Retrieves URL to stream rap audio
      description: |
        Retrieves a signed URL to stream rap audio from
      parameters:
        - in: path
          name: id
          description: The id of the requested rap
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A signed URL to the rap audio
          content:
            text/plain:
              schema:
                type: string
                example: https://vgmdownloads.com/soundtracks/super-mario-64-soundtrack/zfvgdumr/18%20File%20Select.mp3
        '404':
          description: Rap not found
components:
  schemas:
    Rap:
      type: object
      required:
        - title
        - bonus
        - rapper
        - imageUrl
        - appearedAt
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        title:
          type: string
          example: I Get Money
        bonus:
          type: boolean
          example: false
        rapper:
          type: string
          example: Campbell Pedersen
        imageUrl:
          type: string
          example: https://imgur.com/a/DRQDZe8
        appearedAt:
          $ref: '#/components/schemas/Event'
    Event:
      required:
        - name
        - series
      properties:
        name:
          type: string
          example: BSDAC
          enum:
            - BSDAC
        series:
          type: integer
          example: 11
      type: object